name: TryHackMe Badge Action Workflow

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Fetch TryHackMe Badge
      uses: Gepardgame/tryhackme-badge-action-workflow@v0.9
      with:
        image_path: './assets/thm_badge.png'
        username: 'Gepardgame'
        user_id: '567084'
        committer_username: 'github-actions[bot]'
